version: '3'
volumes:
  pgdata:
  static_files:
services:
  web:
    build:
      context: .
      dockerfile: docker/prod/web/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=backend_app.settings.prod
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/debitrum
      - static_files:/static_files
    ports:
      - 8000:8000
    command: gunicorn -w 4 backend_app.wsgi -b 0.0.0.0:8000
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: debitrum
      POSTGRES_DB: debitrum
      POSTGRES_PASS: debitrum
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 80:80

#In the terminal execute the command:
#docker-compose -f prod.yml run web python manage.py collectstatic